### 1. SERVICE - Expone la Aplicaci贸n a Trav茅s del Load Balancer (ELB/ALB)

# Este Service dirige el tr谩fico a CUALQUIER Pod que tenga la etiqueta 'app: duoc-app'.
# Esto incluye tanto la versi贸n Stable como la Canary.
apiVersion: v1
kind: Service
metadata:
  name: duoc-app-canary-service
  labels:
    app: duoc-app
spec:
  #  CLAVE: Este selector apunta a ambos Deployments.
  selector:
    app: duoc-app 
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 3000

---
### 2. DEPLOYMENT - Versi贸n Estable (BLUE)

# Esta es la versi贸n principal, recibiendo la mayor铆a del tr谩fico (90%).
apiVersion: apps/v1
kind: Deployment
metadata:
  name: duoc-app-stable-v1
  labels:
    app: duoc-app
spec:
  #  CLAVE: 9 r茅plicas para el 90% del tr谩fico (9 de 10 Pods totales)
  replicas: 9
  selector:
    matchLabels:
      app: duoc-app
      version: stable
  template:
    metadata:
      labels:
        app: duoc-app
        version: stable # Etiqueta de versi贸n
    spec:
      containers:
      - name: node-app-container
        # 锔 REEMPLAZA: Usa tu imagen de producci贸n V1.0 aqu铆
        image: 885869691689.dkr.ecr.us-east-1.amazonaws.com/duoc-lab:v1.0 
        ports:
        - containerPort: 3000
        imagePullPolicy: Always

---
### 3. DEPLOYMENT - Versi贸n Canary (GREEN)

# Esta es la nueva versi贸n, recibiendo una peque帽a porci贸n del tr谩fico (10%) para pruebas.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: duoc-app-canary-v2
  labels:
    app: duoc-app
spec:
  #  CLAVE: 1 r茅plica para el 10% del tr谩fico (1 de 10 Pods totales)
  replicas: 1
  selector:
    matchLabels:
      app: duoc-app
      version: canary
  template:
    metadata:
      labels:
        app: duoc-app
        version: canary # Etiqueta de versi贸n
    spec:
      containers:
      - name: node-app-container
        # 锔 REEMPLAZA: Usa la nueva imagen V2.0 (Canary) aqu铆
        image: 885869691689.dkr.ecr.us-east-1.amazonaws.com/duoc-lab:v2.0 
        ports:
        - containerPort: 3000
        imagePullPolicy: Always